package com.xcs.requestbribe.p2.request;

import lombok.Data;

@Data
public class RequestRewardStaffinsAllReq extends RequestBribeRequest {

    private String STAFF_ID;
    private String REWARD_ID;
    private String STAFF_REF_ID;
    private String TITLE_ID;
    private String STAFF_CODE;
    private String ID_CARD;
    private String STAFF_TYPE;
    private String TITLE_NAME_TH;
    private String TITLE_NAME_EN;
    private String TITLE_SHORT_NAME_TH;
    private String TITLE_SHORT_NAME_EN;
    private String FIRST_NAME;
    private String LAST_NAME;
    private String AGE;
    private String OPERATION_POS_CODE;
    private String OPREATION_POS_NAME;
    private String OPREATION_POS_LEVEL;
    private String OPERATION_POS_LEVEL_NAME;
    private String OPERATION_DEPT_CODE;
    private String OPERATION_DEPT_NAME;
    private String OPERATION_DEPT_LEVEL;
    private String OPERATION_UNDER_DEPT_CODE;
    private String OPERATION_UNDER_DEPT_NAME;
    private String OPERATION_UNDER_DEPT_LEVEL;
    private String OPERATION_WORK_DEPT_CODE;
    private String OPERATION_WORK_DEPT_NAME;
    private String OPERATION_WORK_DEPT_LEVEL;
    private String OPERATION_OFFICE_CODE;
    private String OPERATION_OFFICE_NAME;
    private String OPERATION_OFFICE_SHORT_NAME;
    private String MANAGEMENT_POS_CODE;
    private String MANAGEMENT_POS_NAME;
    private String MANAGEMENT_POS_LEVEL;
    private String MANAGEMENT_POS_LEVEL_NAME;
    private String MANAGEMENT_DEPT_CODE;
    private String MANAGEMENT_DEPT_NAME;
    private String MANAGEMENT_DEPT_LEVEL;
    private String MANAGEMENT_UNDER_DEPT_CODE;
    private String MANAGEMENT_UNDER_DEPT_NAME;
    private String MANAGEMENT_UNDER_DEPT_LEVEL;
    private String MANAGEMENT_WORK_DEPT_CODE;
    private String MANAGEMENT_WORK_DEPT_NAME;
    private String MANAGEMENT_WORK_DEPT_LEVEL;
    private String MANAGEMENT_OFFICE_CODE;
    private String MANAGEMENT_OFFICE_NAME;
    private String MANAGEMENT_OFFICE_SHORT_NAME;
    private String REPRESENT_POS_CODE;
    private String REPRESENT_POS_NAME;
    private String REPRESENT_POS_LEVEL;
    private String REPRESENT_POS_LEVEL_NAME;
    private String REPRESENT_DEPT_CODE;
    private String REPRESENT_DEPT_NAME;
    private String REPRESENT_DEPT_LEVEL;
    private String REPRESENT_UNDER_DEPT_CODE;
    private String REPRESENT_UNDER_DEPT_NAME;
    private String REPRESENT_UNDER_DEPT_LEVEL;
    private String REPRESENT_WORK_DEPT_CODE;
    private String REPRESENT_WORK_DEPT_NAME;
    private String REPRESENT_WORK_DEPT_LEVEL;
    private String REPRESENT_OFFICE_CODE;
    private String REPRESENT_OFFICE_NAME;
    private String REPRESENT_OFFICE_SHORT_NAME;
    private String STATUS;
    private String REMARK;
    private String FIRST_PART;
    private String FIRST_MONEY;
    private String SECOND_PART;
    private String SECOND_MONEY;
    private String TOTAL_MONEY;
    private String CONTRIBUTOR_ID;
    private String IS_ACTIVE;
    private String SEQ;

}
