package com.xcs.requestbribe.p2.dao;

import com.xcs.requestbribe.p2.model.RequestArrestLawsuitProveCompare;
import com.xcs.requestbribe.p2.model.RequestList;
import com.xcs.requestbribe.p2.request.RequestArrestLawsuitProveComparegetByConReq;
import com.xcs.requestbribe.p2.request.RequestListgetByConAdvReq;
import com.xcs.requestbribe.p2.request.RequestListgetByKeywordReq;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

@Service
@Transactional
public class RequestArrestLawsuitProveCompareDAOImpl extends RequestBribeExt implements RequestArrestLawsuitProveCompareDAO {

    private static final Logger log = LoggerFactory.getLogger(RequestArrestLawsuitProveCompareDAOImpl.class);

    @Override
    public List<RequestArrestLawsuitProveCompare> RequestArrestLawsuitProveComparegetByCon(RequestArrestLawsuitProveComparegetByConReq req) {

        StringBuilder sqlBuilder = new StringBuilder()
                .append(" SELECT DISTINCT OPS_ARREST.ARREST_ID, OPS_ARREST_INDICTMENT.INDICTMENT_ID, OPS_ARREST.ARREST_CODE, TO_CHAR(OPS_ARREST.ARREST_DATE, 'DD MONYYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS ARREST_DATE, TO_CHAR(OPS_ARREST.ARREST_DATE, 'hh24:mi', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS ARREST_TIME, TO_CHAR(OPS_ARREST.OCCURRENCE_DATE, 'DD MONYYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS OCCURRENCE_DATE, TO_CHAR(OPS_ARREST.OCCURRENCE_DATE, 'hh24:mi', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS OCCURRENCE_TIME, CASE WHEN OPS_ARREST_STAFF.TITLE_SHORT_NAME_TH IS NULL OR OPS_ARREST_STAFF.TITLE_SHORT_NAME_TH = 'null' THEN OPS_ARREST_STAFF.TITLE_NAME_TH || '' || OPS_ARREST_STAFF.FIRST_NAME || ' ' || OPS_ARREST_STAFF.LAST_NAME ELSE OPS_ARREST_STAFF.TITLE_SHORT_NAME_TH || '' || OPS_ARREST_STAFF.FIRST_NAME || ' ' || OPS_ARREST_STAFF.LAST_NAME END AS ARREST_STAFF_NAME, OPS_ARREST_STAFF.OPERATION_POS_CODE, OPS_ARREST_STAFF.OPREATION_POS_NAME, OPS_ARREST_STAFF.OPERATION_OFFICE_CODE, OPS_ARREST_STAFF.OPERATION_OFFICE_NAME, OPS_ARREST_STAFF.OPERATION_OFFICE_SHORT_NAME, OPS_ARREST_STAFF.MANAGEMENT_POS_CODE, OPS_ARREST_STAFF.MANAGEMENT_POS_NAME, OPS_ARREST_STAFF.MANAGEMENT_OFFICE_CODE, OPS_ARREST_STAFF.MANAGEMENT_OFFICE_NAME, OPS_ARREST_STAFF.MANAGEMENT_OFFICE_SHORT_NAME, OPS_ARREST.OFFICE_NAME ARREST_OFFICE_NAME, MAS_SUB_DISTRICT.SUB_DISTRICT_NAME_TH, MAS_SUB_DISTRICT.SUB_DISTRICT_NAME_EN, MAS_DISTRICT.DISTRICT_NAME_TH, MAS_DISTRICT.DISTRICT_NAME_EN, MAS_PROVINCE.PROVINCE_NAME_TH, MAS_PROVINCE.PROVINCE_NAME_EN, MAS_LAW_GROUP_SECTION.SECTION_NAME, MAS_LAW_GROUP_SUBSECTION.SUBSECTION_ID, MAS_LAW_GROUP_SUBSECTION.SUBSECTION_NAME, MAS_LAW_GUILTBASE.GUILTBASE_NAME, MAS_LAW_PENALTY.SECTION_ID, MAS_LAW_PENALTY.PENALTY_DESC, OPS_ARREST.IS_ACTIVE ARREST_IS_ACTIVE, OPS_LAWSUIT.LAWSUIT_ID, OPS_LAWSUIT.INDICTMENT_ID LAWSUIT_INDICTMENT_ID, CASE WHEN OPS_LAWSUIT.IS_OUTSIDE = '1' THEN 'น. ' END || OPS_LAWSUIT.LAWSUIT_NO || CASE WHEN OPS_LAWSUIT.LAWSUIT_NO IS NOT NULL THEN '/' END || TO_CHAR(OPS_LAWSUIT.LAWSUIT_NO_YEAR, 'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS LAWSUIT_NO, TO_CHAR(OPS_LAWSUIT.LAWSUIT_NO_YEAR, 'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS LAWSUIT_NO_YEAR, TO_CHAR(OPS_LAWSUIT.LAWSUIT_DATE, 'DD MONYYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS LAWSUIT_DATE, TO_CHAR(OPS_LAWSUIT.LAWSUIT_DATE,'hh24:mi','NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS LAWSUIT_TIME, OPS_LAWSUIT.OFFICE_NAME LAWSUIT_OFFICE_NAME, OPS_LAWSUIT.IS_ACTIVE LAWSUIT_IS_ACTIVE, OPS_LAWSUIT_DETAIL.LAWSUIT_DETAIL_ID LAWSUIT_LAWSUIT_DETAIL_ID, OPS_LAWSUIT_DETAIL.COURT_ID, OPS_LAWSUIT_DETAIL.LAWSUIT_TYPE, OPS_LAWSUIT_DETAIL.COURT_NAME, OPS_LAWSUIT_DETAIL.UNDECIDE_NO_1, OPS_LAWSUIT_DETAIL.UNDECIDE_NO_YEAR_1, OPS_LAWSUIT_DETAIL.DECIDE_NO_1, OPS_LAWSUIT_DETAIL.DECIDE_NO_YEAR_1, OPS_LAWSUIT_DETAIL.UNDECIDE_NO_2, OPS_LAWSUIT_DETAIL.UNDECIDE_NO_YEAR_2, OPS_LAWSUIT_DETAIL.DECIDE_NO_2, OPS_LAWSUIT_DETAIL.DECIDE_NO_YEAR_2, OPS_LAWSUIT_DETAIL.JUDGEMENT_NO, OPS_LAWSUIT_DETAIL.JUDGEMENT_NO_YEAR, OPS_LAWSUIT_DETAIL.IS_FINE, OPS_LAWSUIT_DETAIL.FINE LAWSUIT_DETAIL_FINE, OPS_LAWSUIT_DETAIL.IS_PAYONCE, OPS_LAWSUIT_DETAIL.FINE_DATE, OPS_LAWSUIT_DETAIL.PAYMENT_PERIOD, OPS_LAWSUIT_DETAIL.PAYMENT_PERIOD_DUE, OPS_LAWSUIT_DETAIL.PAYMENT_PERIOD_DUE_UNIT, OPS_LAWSUIT_DETAIL.PAYMENT_DATE LAWSUIT_DETAIL_PAYMENT_DATE, OPS_LAWSUIT_DETAIL.IS_DISMISS, OPS_LAWSUIT_DETAIL.IS_ACTIVE LAWSUIT_DETAIL_IS_ACTIVE, OPS_LAWSUIT_DETAIL.UNJUDGEMENT_NO, OPS_LAWSUIT_DETAIL.UNJUDGEMENT_NO_YEAR, OPS_PAYMENT.PAYMENT_ID, OPS_PAYMENT.LAWSUIT_DETAIL_ID PAYMENT_LAWSUIT_DETAIL_ID, OPS_PAYMENT.COMPARE_DETAIL_ID PAYMENT_COMPARE_DETAIL_ID, OPS_PAYMENT.FINE_TYPE, OPS_PAYMENT.FINE PAYMENT_FINE, OPS_PAYMENT.PAYMENT_PERIOD_NO, OPS_PAYMENT.PAYMENT_DATE PAYMENT_PAYMENT_DATE, OPS_PAYMENT.IS_REQUEST_REWARD, OPS_PAYMENT.IS_ACTIVE, OPS_PAYMENT.PAYMENT_CHANNEL, OPS_PAYMENT.PAYMENT_BANK, OPS_PAYMENT.PAYMENT_REF_NO, OPS_PAYMENT.IS_REVENUE, OPS_NOTICE.NOTICE_ID, OPS_NOTICE.ARREST_ID NOTICE_ARREST_ID, OPS_NOTICE.NOTICE_CODE, TO_CHAR(OPS_NOTICE.NOTICE_DATE, 'DD MONYYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS NOTICE_DATE, TO_CHAR(OPS_NOTICE.NOTICE_DATE, 'hh24:mi', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS NOTICE_TIME, CASE WHEN OPS_NOTICE_INFORMER.INFORMER_STATUS = '0' THEN OPS_NOTICE_INFORMER.FIRST_NAME WHEN OPS_NOTICE_INFORMER.INFORMER_STATUS = '1' THEN OPS_NOTICE_INFORMER.TITLE_SHORT_NAME_TH || '' || OPS_NOTICE_INFORMER.FIRST_NAME || ' ' || OPS_NOTICE_INFORMER.MIDDLE_NAME || ' ' || OPS_NOTICE_INFORMER.LAST_NAME END AS NOTICE_INFORMER, OPS_NOTICE_STAFF.TITLE_SHORT_NAME_TH || '' || OPS_NOTICE_STAFF.FIRST_NAME || ' ' || OPS_NOTICE_STAFF.LAST_NAME AS NOTICE_STAFF, OPS_NOTICE_STAFF.OPERATION_POS_CODE NOTICE_OPREATION_POS_CODE, OPS_NOTICE_STAFF.OPREATION_POS_NAME NOTICE_OPREATION_POS_NAME, OPS_NOTICE_STAFF.OPERATION_OFFICE_CODE NOTICE_OPERATION_OFFICE_CODE, OPS_NOTICE_STAFF.OPERATION_OFFICE_NAME NOTICE_OPERATION_OFFICE_NAME, OPS_NOTICE_STAFF.OPERATION_OFFICE_SHORT_NAME NOTICE_OPER_OFFICE_SHORT_NAME, OPS_NOTICE_STAFF.MANAGEMENT_POS_CODE NOTICE_MANAGEMENT_POS_CODE, OPS_NOTICE_STAFF.MANAGEMENT_POS_NAME NOTICE_MANAGEMENT_POS_NAME, OPS_NOTICE_STAFF.MANAGEMENT_OFFICE_CODE NOTICE_MANAGEMENT_OFFICE_CODE, OPS_NOTICE_STAFF.MANAGEMENT_OFFICE_NAME NOTICE_MANAGEMENT_OFFICE_NAME, OPS_NOTICE_STAFF.MANAGEMENT_OFFICE_SHORT_NAME NOTICE_MANA_OFFICE_SHORT_NAME, OPS_NOTICE.OFFICE_NAME NOTICE_OFFICE_NAME, OPS_NOTICE_STAFF.CONTRIBUTOR_ID, OPS_NOTICE.IS_ACTIVE NOTICE_IS_ACTIVE, OPS_COMPARE.COMPARE_ID, OPS_COMPARE_DETAIL.COMPARE_DETAIL_ID COMPARE_COMPARE_DETAIL_ID, OPS_COMPARE.LAWSUIT_ID COMPARE_LAWSUIT_ID, CASE WHEN OPS_COMPARE.IS_OUTSIDE = '1' THEN 'น. ' END || OPS_COMPARE.COMPARE_NO || CASE WHEN OPS_COMPARE.COMPARE_NO IS NOT NULL THEN '/' END || TO_CHAR(OPS_COMPARE.COMPARE_NO_YEAR, 'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS COMPARE_NO, TO_CHAR(OPS_COMPARE.COMPARE_NO_YEAR, 'YYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS COMPARE_NO_YEAR, TO_CHAR(OPS_COMPARE.COMPARE_DATE, 'DD MONYYYY', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS COMPARE_DATE, TO_CHAR(OPS_COMPARE.COMPARE_DATE, 'hh24:mi', 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI') AS COMPARE_TIME, OPS_COMPARE.OFFICE_NAME COMPARE_OFFICE_NAME, OPS_COMPARE_DETAIL.PAYMENT_FINE COMPARE_DETAIL_PAYMENT_FINE, OPS_COMPARE_DETAIL.TREASURY_MONEY, OPS_COMPARE_DETAIL.BRIBE_MONEY, OPS_COMPARE_DETAIL.REWARD_MONEY, OPS_COMPARE.IS_ACTIVE COMPARE_IS_ACTIVE FROM OPS_ARREST INNER JOIN OPS_ARREST_STAFF ON OPS_ARREST_STAFF.ARREST_ID=OPS_ARREST.ARREST_ID AND OPS_ARREST_STAFF.CONTRIBUTOR_ID='14' INNER JOIN OPS_ARREST_INDICTMENT ON OPS_ARREST_INDICTMENT.ARREST_ID = OPS_ARREST.ARREST_ID INNER JOIN OPS_ARREST_LOCALE ON OPS_ARREST.ARREST_ID = OPS_ARREST_LOCALE.ARREST_ID INNER JOIN MAS_SUB_DISTRICT ON OPS_ARREST_LOCALE.SUB_DISTRICT_ID = MAS_SUB_DISTRICT.SUB_DISTRICT_ID INNER JOIN MAS_DISTRICT ON MAS_SUB_DISTRICT.DISTRICT_ID = MAS_DISTRICT.DISTRICT_ID INNER JOIN MAS_PROVINCE ON MAS_DISTRICT.PROVINCE_ID = MAS_PROVINCE.PROVINCE_ID INNER JOIN MAS_LAW_GUILTBASE ON OPS_ARREST_INDICTMENT.GUILTBASE_ID = MAS_LAW_GUILTBASE.GUILTBASE_ID INNER JOIN MAS_LAW_GROUP_SUBSECTION_RULE ON MAS_LAW_GUILTBASE.SUBSECTION_RULE_ID = MAS_LAW_GROUP_SUBSECTION_RULE.SUBSECTION_RULE_ID INNER JOIN MAS_LAW_GROUP_SUBSECTION ON MAS_LAW_GROUP_SUBSECTION_RULE.SUBSECTION_ID = MAS_LAW_GROUP_SUBSECTION.SUBSECTION_ID INNER JOIN MAS_LAW_GROUP_SECTION ON MAS_LAW_GROUP_SUBSECTION.SECTION_ID = MAS_LAW_GROUP_SECTION.SECTION_ID INNER JOIN MAS_LAW_GROUP_SUBSECTION ON MAS_LAW_GROUP_SUBSECTION_RULE.SUBSECTION_ID = MAS_LAW_GROUP_SUBSECTION.SUBSECTION_ID INNER JOIN MAS_LAW_PENALTY ON MAS_LAW_GROUP_SUBSECTION.SECTION_ID = MAS_LAW_PENALTY.SECTION_ID LEFT JOIN OPS_LAWSUIT ON OPS_ARREST_INDICTMENT.INDICTMENT_ID = OPS_LAWSUIT.INDICTMENT_ID LEFT JOIN OPS_LAWSUIT_DETAIL ON OPS_LAWSUIT.LAWSUIT_ID = OPS_LAWSUIT_DETAIL.LAWSUIT_ID LEFT JOIN OPS_PAYMENT ON OPS_LAWSUIT_DETAIL.LAWSUIT_DETAIL_ID = OPS_PAYMENT.LAWSUIT_DETAIL_ID LEFT JOIN OPS_COMPARE ON OPS_LAWSUIT.LAWSUIT_ID = OPS_COMPARE.LAWSUIT_ID AND OPS_COMPARE.IS_ACTIVE = '1' LEFT JOIN OPS_COMPARE_MAPPING ON OPS_COMPARE.COMPARE_ID = OPS_COMPARE_MAPPING.COMPARE_ID LEFT JOIN OPS_COMPARE_DETAIL ON OPS_COMPARE_MAPPING.COMPARE_MAPPING_ID = OPS_COMPARE_DETAIL.COMPARE_MAPPING_ID LEFT JOIN OPS_COMPARE_DETAIL_PAYMENT ON OPS_COMPARE_DETAIL.COMPARE_DETAIL_ID = OPS_COMPARE_DETAIL_PAYMENT.COMPARE_DETAIL_ID LEFT JOIN OPS_NOTICE ON OPS_ARREST.ARREST_ID = OPS_NOTICE.ARREST_ID LEFT JOIN OPS_NOTICE_STAFF ON OPS_NOTICE.NOTICE_ID = OPS_NOTICE_STAFF.NOTICE_ID AND OPS_NOTICE_STAFF.CONTRIBUTOR_ID IN('7','8') LEFT JOIN OPS_NOTICE_INFORMER ON OPS_NOTICE.NOTICE_ID = OPS_NOTICE_INFORMER.NOTICE_ID AND OPS_NOTICE_INFORMER.IS_ACTIVE = '1' WHERE OPS_ARREST_STAFF.IS_ACTIVE = 1 AND OPS_ARREST_INDICTMENT.IS_ACTIVE = 1 AND OPS_LAWSUIT.IS_ACTIVE = 1 AND OPS_ARREST_INDICTMENT.IS_LAWSUIT_COMPLETE = 1 ");

        if (req.getINDICTMENT_ID() != null && !"".equals(req.getINDICTMENT_ID())) {

            sqlBuilder.append(" AND OPS_ARREST_INDICTMENT.INDICTMENT_ID = '" + req.getINDICTMENT_ID() + "' ");

        }

        log.info("[SQL]  : " + sqlBuilder.toString());

        @SuppressWarnings("unchecked")
        List<RequestArrestLawsuitProveCompare> dataList = getJdbcTemplate().query(sqlBuilder.toString(), new RowMapper<RequestArrestLawsuitProveCompare>() {

            public RequestArrestLawsuitProveCompare mapRow(ResultSet rs, int rowNum) throws SQLException {

                RequestArrestLawsuitProveCompare item = new RequestArrestLawsuitProveCompare();

                item.setARREST_ID(rs.getString("ARREST_ID"));
                item.setINDICTMENT_ID(rs.getString("INDICTMENT_ID"));
                item.setARREST_CODE(rs.getString("ARREST_CODE"));
                item.setARREST_DATE(rs.getString("ARREST_DATE"));
                item.setARREST_TIME(rs.getString("ARREST_TIME"));
                item.setOCCURRENCE_DATE(rs.getString("OCCURRENCE_DATE"));
                item.setOCCURRENCE_TIME(rs.getString("OCCURRENCE_TIME"));
                item.setARREST_STAFF_NAME(rs.getString("ARREST_STAFF_NAME"));
                item.setOPERATION_POS_CODE(rs.getString("OPERATION_POS_CODE"));
                item.setOPREATION_POS_NAME(rs.getString("OPREATION_POS_NAME"));
                item.setOPERATION_OFFICE_CODE(rs.getString("OPERATION_OFFICE_CODE"));
                item.setOPERATION_OFFICE_NAME(rs.getString("OPERATION_OFFICE_NAME"));
                item.setOPERATION_OFFICE_SHORT_NAME(rs.getString("OPERATION_OFFICE_SHORT_NAME"));
                item.setMANAGEMENT_POS_CODE(rs.getString("MANAGEMENT_POS_CODE"));
                item.setMANAGEMENT_POS_NAME(rs.getString("MANAGEMENT_POS_NAME"));
                item.setMANAGEMENT_OFFICE_CODE(rs.getString("MANAGEMENT_OFFICE_CODE"));
                item.setMANAGEMENT_OFFICE_NAME(rs.getString("MANAGEMENT_OFFICE_NAME"));
                item.setMANAGEMENT_OFFICE_SHORT_NAME(rs.getString("MANAGEMENT_OFFICE_SHORT_NAME"));
                item.setARREST_OFFICE_NAME(rs.getString("ARREST_OFFICE_NAME"));
                item.setSUB_DISTRICT_NAME_TH(rs.getString("SUB_DISTRICT_NAME_TH"));
                item.setSUB_DISTRICT_NAME_EN(rs.getString("SUB_DISTRICT_NAME_EN"));
                item.setDISTRICT_NAME_TH(rs.getString("DISTRICT_NAME_TH"));
                item.setDISTRICT_NAME_EN(rs.getString("DISTRICT_NAME_EN"));
                item.setPROVINCE_NAME_TH(rs.getString("PROVINCE_NAME_TH"));
                item.setPROVINCE_NAME_EN(rs.getString("PROVINCE_NAME_EN"));
                item.setSECTION_NAME(rs.getString("SECTION_NAME"));
                item.setSUBSECTION_ID(rs.getString("SUBSECTION_ID"));
                item.setSUBSECTION_NAME(rs.getString("SUBSECTION_NAME"));
                item.setGUILTBASE_NAME(rs.getString("GUILTBASE_NAME"));
                item.setSECTION_ID(rs.getString("SECTION_ID"));
                item.setPENALTY_DESC(rs.getString("PENALTY_DESC"));
                item.setARREST_IS_ACTIVE(rs.getString("ARREST_IS_ACTIVE"));
                item.setLAWSUIT_ID(rs.getString("LAWSUIT_ID"));
                item.setLAWSUIT_INDICTMENT_ID(rs.getString("LAWSUIT_INDICTMENT_ID"));
                item.setLAWSUIT_NO(rs.getString("LAWSUIT_NO"));
                item.setLAWSUIT_NO_YEAR(rs.getString("LAWSUIT_NO_YEAR"));
                item.setLAWSUIT_DATE(rs.getString("LAWSUIT_DATE"));
                item.setLAWSUIT_TIME(rs.getString("LAWSUIT_TIME"));
                item.setLAWSUIT_OFFICE_NAME(rs.getString("LAWSUIT_OFFICE_NAME"));
                item.setLAWSUIT_IS_ACTIVE(rs.getString("LAWSUIT_IS_ACTIVE"));

                item.setLAWSUIT_DETAIL_LAWSUIT_DETAIL_ID(rs.getString("LAWSUIT_LAWSUIT_DETAIL_ID"));
                item.setCOURT_ID(rs.getString("COURT_ID"));
                item.setLAWSUIT_TYPE(rs.getString("LAWSUIT_TYPE"));
                item.setCOURT_NAME(rs.getString("COURT_NAME"));
                item.setUNDECIDE_NO_1(rs.getString("UNDECIDE_NO_1"));
                item.setUNDECIDE_NO_YEAR_1(rs.getString("UNDECIDE_NO_YEAR_1"));
                item.setDECIDE_NO_1(rs.getString("DECIDE_NO_1"));
                item.setDECIDE_NO_YEAR_1(rs.getString("DECIDE_NO_YEAR_1"));
                item.setUNDECIDE_NO_2(rs.getString("UNDECIDE_NO_2"));
                item.setUNDECIDE_NO_YEAR_2(rs.getString("UNDECIDE_NO_YEAR_2"));
                item.setDECIDE_NO_2(rs.getString("DECIDE_NO_2"));
                item.setDECIDE_NO_YEAR_2(rs.getString("DECIDE_NO_YEAR_2"));
                item.setJUDGEMENT_NO(rs.getString("JUDGEMENT_NO"));
                item.setJUDGEMENT_NO_YEAR(rs.getString("JUDGEMENT_NO_YEAR"));
                item.setIS_FINE(rs.getString("IS_FINE"));
                item.setLAWSUIT_DETAIL_FINE(rs.getString("LAWSUIT_DETAIL_FINE"));
                item.setIS_PAYONCE(rs.getString("IS_PAYONCE"));
                item.setFINE_DATE(rs.getString("FINE_DATE"));
                item.setPAYMENT_PERIOD(rs.getString("PAYMENT_PERIOD"));
                item.setPAYMENT_PERIOD_DUE(rs.getString("PAYMENT_PERIOD_DUE"));
                item.setPAYMENT_PERIOD_DUE_UNIT(rs.getString("PAYMENT_PERIOD_DUE_UNIT"));
                item.setLAWSUIT_DETAIL_PAYMENT_DATE(rs.getString("LAWSUIT_DETAIL_PAYMENT_DATE"));
                item.setIS_DISMISS(rs.getString("IS_DISMISS"));
                item.setLAWSUIT_DETAIL_IS_ACTIVE(rs.getString("LAWSUIT_DETAIL_IS_ACTIVE"));
                item.setUNJUDGEMENT_NO(rs.getString("UNJUDGEMENT_NO"));
                item.setUNJUDGEMENT_NO_YEAR(rs.getString("UNJUDGEMENT_NO_YEAR"));
                item.setPAYMENT_ID(rs.getString("PAYMENT_ID"));
                item.setPAYMENT_LAWSUIT_DETAIL_ID(rs.getString("PAYMENT_LAWSUIT_DETAIL_ID"));
                item.setPAYMENT_COMPARE_DETAIL_ID(rs.getString("PAYMENT_COMPARE_DETAIL_ID"));
                item.setFINE_TYPE(rs.getString("FINE_TYPE"));
                item.setPAYMENT_FINE(rs.getString("PAYMENT_FINE"));
                item.setPAYMENT_PERIOD_NO(rs.getString("PAYMENT_PERIOD_NO"));
                item.setPAYMENT_PAYMENT_DATE(rs.getString("PAYMENT_PAYMENT_DATE"));
                item.setIS_REQUEST_REWARD(rs.getString("IS_REQUEST_REWARD"));
                item.setIS_ACTIVE(rs.getString("IS_ACTIVE"));
                item.setPAYMENT_CHANNEL(rs.getString("PAYMENT_CHANNEL"));
                item.setPAYMENT_BANK(rs.getString("PAYMENT_BANK"));
                item.setPAYMENT_REF_NO(rs.getString("PAYMENT_REF_NO"));
                item.setIS_REVENUE(rs.getString("IS_REVENUE"));

                item.setNOTICE_ID(rs.getString("NOTICE_ID"));
                item.setNOTICE_ARREST_ID(rs.getString("NOTICE_ARREST_ID"));
                item.setNOTICE_CODE(rs.getString("NOTICE_CODE"));
                item.setNOTICE_DATE(rs.getString("NOTICE_DATE"));
                item.setNOTICE_TIME(rs.getString("NOTICE_TIME"));
                item.setNOTICE_INFORMER(rs.getString("NOTICE_INFORMER"));
                item.setNOTICE_STAFF(rs.getString("NOTICE_STAFF"));
                item.setNOTICE_OPREATION_POS_CODE(rs.getString("NOTICE_OPREATION_POS_CODE"));
                item.setNOTICE_OPREATION_POS_NAME(rs.getString("NOTICE_OPREATION_POS_NAME"));
                item.setNOTICE_OPERATION_OFFICE_CODE(rs.getString("NOTICE_OPERATION_OFFICE_CODE"));
                item.setNOTICE_OPERATION_OFFICE_NAME(rs.getString("NOTICE_OPERATION_OFFICE_NAME"));
                item.setNOTICE_OPERATION_OFFICE_SHORT_NAME(rs.getString("NOTICE_OPER_OFFICE_SHORT_NAME"));
                item.setNOTICE_MANAGEMENT_POS_CODE(rs.getString("NOTICE_MANAGEMENT_POS_CODE"));
                item.setNOTICE_MANAGEMENT_POS_NAME(rs.getString("NOTICE_MANAGEMENT_POS_NAME"));
                item.setNOTICE_MANAGEMENT_OFFICE_CODE(rs.getString("NOTICE_MANAGEMENT_OFFICE_CODE"));
                item.setNOTICE_MANAGEMENT_OFFICE_NAME(rs.getString("NOTICE_MANAGEMENT_OFFICE_NAME"));
                item.setNOTICE_MANAGEMENT_OFFICE_SHORT_NAME(rs.getString("NOTICE_MANA_OFFICE_SHORT_NAME"));
                item.setNOTICE_OFFICE_NAME(rs.getString("NOTICE_OFFICE_NAME"));
                item.setCONTRIBUTOR_ID(rs.getString("CONTRIBUTOR_ID"));
                item.setNOTICE_IS_ACTIVE(rs.getString("NOTICE_IS_ACTIVE"));
                item.setCOMPARE_ID(rs.getString("COMPARE_ID"));
                item.setCOMPARE_DETAIL_COMPARE_DETAIL_ID(rs.getString("COMPARE_COMPARE_DETAIL_ID"));
                item.setCOMPARE_LAWSUIT_ID(rs.getString("COMPARE_LAWSUIT_ID"));
                item.setCOMPARE_NO(rs.getString("COMPARE_NO"));
                item.setCOMPARE_NO_YEAR(rs.getString("COMPARE_NO_YEAR"));
                item.setCOMPARE_DATE(rs.getString("COMPARE_DATE"));
                item.setCOMPARE_TIME(rs.getString("COMPARE_TIME"));
                item.setCOMPARE_OFFICE_NAME(rs.getString("COMPARE_OFFICE_NAME"));
                item.setCOMPARE_DETAIL_PAYMENT_FINE(rs.getString("COMPARE_DETAIL_PAYMENT_FINE"));
                item.setTREASURY_MONEY(rs.getString("TREASURY_MONEY"));
                item.setBRIBE_MONEY(rs.getString("BRIBE_MONEY"));
                item.setREWARD_MONEY(rs.getString("REWARD_MONEY"));
                item.setCOMPARE_IS_ACTIVE(rs.getString("COMPARE_IS_ACTIVE"));

                return item;

            }

        });

        return dataList;

    }

}
